# Generated by Django 3.2.9 on 2021-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('api_id', models.TextField()),
                ('api_hash', models.TextField()),
            ],
        ),
    ]
